cast_delay: 10
device_map:
  "<YOUR_DISPLAY_NAME>": "YOUR_DASHBOARD_URL"
  "<YOUR_DISPLAY_NAME>": "YOUR_DASHBOARD_URL"
  "<YOUR_DISPLAY_NAME>": "YOUR_DASHBOARD_URL"
  # eg: "Office display": "http://192.168.12.104:8123/office-dashboard/default_view?kiosk"
  # eg: "Kitchen display": "http://192.168.12.104:8123/kitchen-dashboard/default_view?kiosk"
